name: Deploy

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Upload files to Webuzo
        uses: appleboy/scp-action@v0.1.7
        with:
          host: mycloud.himalayan.host
          username: sayteoco
          port: 8186
          key: ${{ secrets.WEBUZO_SSH_KEY }}
          source: "."
          target: "/home2/sayteoco/test"

      - name: Install, build and restart app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: mycloud.himalayan.host
          username: sayteoco
          port: 8186
          key: ${{ secrets.WEBUZO_SSH_KEY }}
          script: |
            cd /home2/sayteoco/test
            npm install
            npm run build
            npx pm2 restart next-app || npx pm2 start npm --name next-app -- start
            npx pm2 save
