name: Deploy

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Deploy files to Webuzo FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 161.129.67.102
          username: sayteoco
          password: r9bEYku217(E!Y
          local-dir: ./
          server-dir: /test/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.next/**
